set(CASABLANCA_VERSION_MAJOR 2)
set(CASABLANCA_VERSION_MINOR 6)
set(CASABLANCA_VERSION_STRING "${CASABLANCA_VERSION_MAJOR}_${CASABLANCA_VERSION_MINOR}")
set(CASABLANCA_VISUAL_STUDIO_VERSION_STRING "140")

find_path(CASABLANCA_INCLUDE_DIRS
  cpprest/http_client.h
  HINTS $ENV{CASABLANCA_ROOT}
  PATH_SUFFIXES SDK/include Release/include
)

find_library(CASABLANCA_LIB_DEBUG
  cpprest${CASABLANCA_VISUAL_STUDIO_VERSION_STRING}d_${CASABLANCA_VERSION_STRING}
  HINTS $ENV{CASABLANCA_ROOT}
  PATH_SUFFIXES SDK/lib/x64/Debug Binaries/x64/Debug
)

find_library(CASABLANCA_LIB_RELEASE
  cpprest${CASABLANCA_VISUAL_STUDIO_VERSION_STRING}_${CASABLANCA_VERSION_STRING}
  HINTS $ENV{CASABLANCA_ROOT}
  PATH_SUFFIXES SDK/lib/x64/Release Binaries/x64/Release
)

find_file(CASABLANCA_DLL_DEBUG
  cpprest${CASABLANCA_VISUAL_STUDIO_VERSION_STRING}d_${CASABLANCA_VERSION_STRING}.dll
  HINTS $ENV{CASABLANCA_ROOT}
  PATH_SUFFIXES SDK/bin/x64/Debug Binaries/x64/Debug
)

find_file(CASABLANCA_PDB_DEBUG
  cpprest${CASABLANCA_VISUAL_STUDIO_VERSION_STRING}d_${CASABLANCA_VERSION_STRING}.pdb
  HINTS $ENV{CASABLANCA_ROOT}
  PATH_SUFFIXES SDK/bin/x64/Debug Binaries/x64/Debug
)

find_file(CASABLANCA_DLL_RELEASE
  cpprest${CASABLANCA_VISUAL_STUDIO_VERSION_STRING}_${CASABLANCA_VERSION_STRING}.dll
  HINTS $ENV{CASABLANCA_ROOT}
  PATH_SUFFIXES SDK/bin/x64/Release Binaries/x64/Release
)

if(CASABLANCA_LIB_DEBUG AND CASABLANCA_LIB_RELEASE)
  set(CASABLANCA_LIBRARIES debug ${CASABLANCA_LIB_DEBUG} optimized ${CASABLANCA_LIB_RELEASE} CACHE STRING "")
endif()

if(CASABLANCA_DLL_DEBUG AND CASABLANCA_PDB_DEBUG AND CASABLANCA_DLL_RELEASE)
  set(CASABLANCA_DLLS ${CASABLANCA_DLL_DEBUG} ${CASABLANCA_PDB_DEBUG} ${CASABLANCA_DLL_RELEASE} CACHE STRING "")
endif()
